server:
  port: 8088

spring:
  datasource:
    username: combat_game_only
    password: AB1EEACFC9B5
    url: jdbc:mysql://database.xxle.cf:3306/combat_db?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true # 我这边看到的备注是乱码内容？？？ maybe we should use utf8 encoding.
      additional-paths: src/main/java/**